[versions]

kotlin = "1.7.22"
androidGradlePlugin = "7.3.1"
androidMaterial = "1.7.0"
navigation = "2.5.3"
dependencyUpdates = "0.44.0"

[libraries]
# ANDROID
android-androidMaterial = { module = "com.google.android.material:material", version.ref = "androidMaterial" }
android-navigation = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }

# CLASSPATHS
classpaths-androidGradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
classpaths-kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]

android = { id = "org.jetbrains.kotlin.android" }
androidLib = { id = "com.android.library" }
dependencyUpdates = { id = "com.github.ben-manes.versions", version.ref = "dependencyUpdates" }
