[versions]

androidGradlePlugin = "9.2.1"
androidMaterial = "1.14.0"
navigation = "2.9.8"
mavenPublish = "0.37.0"

[libraries]
# ANDROID
android-androidMaterial = { module = "com.google.android.material:material", version.ref = "androidMaterial" }
android-navigation = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }

[plugins]

androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
