[versions]

androidGradlePlugin = "9.0.1"
androidMaterial = "1.13.0"
navigation = "2.9.6"

[libraries]
# ANDROID
android-androidMaterial = { module = "com.google.android.material:material", version.ref = "androidMaterial" }
android-navigation = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }

[plugins]

androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
