[versions]

kotlin = "1.9.20"
androidGradlePlugin = "8.1.3"
androidMaterial = "1.10.0"
navigation = "2.7.4"

[libraries]
# ANDROID
android-androidMaterial = { module = "com.google.android.material:material", version.ref = "androidMaterial" }
android-navigation = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }

[plugins]

kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
