name: BaseMob CI

on:
  push:
    branches:
      - develop
      - 'submodule/CCC'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - name: Setup Gradle Repo
        uses: Oztechan/Global/actions/setup-gradle-repo@d5c2d633506a792e53d7a273d90dde429df3bba7

      - name: Gradle Build
        run: ./gradlew build

      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1.6.0
        with:
          channel: submob
          status: FAILED
          color: danger