name: BaseMob CI

on:
  push:
    branches:
      - develop
      - 'submodule/CCC'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2.6.0
        with:
          arguments: build

      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v2
        with:
          channel: submob
          status: FAILED
          color: danger